import { ref } from "vue";

export let currentService = ref(null);
export let services = ref([
    {
        active: 1,
        api_key: "",
        cors: "*",
        created_locale: "KR",
        email: "kkb7528@broadwayinc.com",
        email_triggers: {
            template_setters: {
                invitation: "ap215YqmUTiOMJOKCmGr-tpca05252fb8227531be810e959d100136@mail.skapi.app",
                newsletter_subscription: "ap215YqmUTiOMJOKCmGr-tp75795a7ddc50c31d252afd5c7796a498@mail.skapi.app",
                signup_confirmation: "ap215YqmUTiOMJOKCmGr-tpd7cb9cc07adc726904fa48197b2b1b7f@mail.skapi.app",
                verification: "ap215YqmUTiOMJOKCmGr-tp886587461e82676d00368443c2176e4a@mail.skapi.app",
                welcome: "ap215YqmUTiOMJOKCmGr-tp80763d2756bcba239fde604716d48902@mail.skapi.app"
            }
        },
        group: 1,
        host: "eu71zettahertzesskpi",
        name: "newkkk",
        newsletter_subscribers: 0,
        owner: "5750ee2c-f7f7-43ff-b6a5-cce599d30101",
        region: "ap-northeast-1",
        service: "ap215YqmUTiOMJOKCmGr",
        subsInfo: {
            application: null,
            application_fee_percent: null,
            automatic_tax: {enabled: false, liability: null},
            billing_cycle_anchor: 1709104399,
            billing_cycle_anchor_config: null,
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: {comment: null, feedback: null, reason: null},
            collection_method: "charge_automatically",
            created: 1709104399,
            currency: "usd",
            current_period_end: 1711609999,
            current_period_start: 1709104399,
            customer: "cus_PW1FKUxikUZZ14",
            days_until_due: null,
            default_payment_method: "pm_1Ony4IHfHjKTnB396hlH4Hxf",
            default_source: null,
            default_tax_rates: [],
            description: "Subscription Plan of service ID: ap215YqmUTiOMJOKCmGr",
            discount: null,
            ended_at: null,
            id: "sub_1OohKNHfHjKTnB39OBN7zrBc",
            invoice_settings: {account_tax_ids: null, issuer: {type: 'self'}},
            items: {
                object: 'list', 
                data: [
                    {   
                        billing_thresholds: null,
                        created: 1709104399,
                        id: "si_PdzIWXUPqtiBHB",
                        metadata: {},
                        object: "subscription_item",
                        plan: {
                            active: true,
                            aggregate_usage: null,
                            amount: 1900,
                            amount_decimal: "1900",
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            interval: "month",
                            interval_count: 1,
                            livemode: false,
                            metadata: {},
                            nickname: null,
                            object: "plan",
                            product: "prod_PIoWQwwkbSIBHu",
                            tiers_mode: null,
                            transform_usage: null,
                            trial_period_day: null,
                            usage_type: "licensed"
                        },
                        price: {
                            active: true,
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            custom_unit_amount: null,
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            livemode: false,
                            lookup_key: null,
                            metadata: {},
                            nickname: null,
                            object: "price",
                            product: "prod_PIoWQwwkbSIBHu",
                            recurring: {aggregate_usage: null, interval: 'month', interval_count: 1, trial_period_days: null, usage_type: 'licensed'},
                            tax_behavior: "unspecified",
                            tiers_mode: null,
                            transform_quantity: null,
                            type: "recurring",
                            unit_amount: 1900,
                            unit_amount_decimal: "1900"
                        },
                        quantity: 1,
                        subscription: "sub_1OohKNHfHjKTnB39OBN7zrBc",
                        tax_rates: []
                    }
                ],
                has_more: false, 
                total_count: 1, 
                url: '/v1/subscription_items?subscription=sub_1OohKNHfHjKTnB39OBN7zrBc'
            },
            latest_invoice: "in_1OohKNHfHjKTnB3958nizZVD",
            livemode: false,
            metadata: {owner: '5750ee2c-f7f7-43ff-b6a5-cce599d30101', service: 'ap215YqmUTiOMJOKCmGr'},
            next_pending_invoice_item_invoice: null,
            object: "subscription",
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: {network: null, request_three_d_secure: 'automatic'},
                    customer_balance: null,
                    konbini: null,
                    us_bank_account: null
                },
                payment_method_types: null,
                save_default_payment_method: "off"
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                active: true,
                aggregate_usage: null,
                amount: 1900,
                amount_decimal: "1900",
                billing_scheme: "per_unit",
                created: 1704220828,
                currency: "usd",
                id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                object: "plan",
                product: "prod_PIoWQwwkbSIBHu",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed"
            },
            quantity: 1,
            schedule: null,
            start_date: 1709104399,
            status: "active",
            test_clock: null,
            transfer_data: null,
            trial_end: null,
            trial_settings: {
                end_behavior: {missing_payment_method: 'create_invoice'}
            },
            trial_start: null
        },
        subs_id: "sub_1OohKNHfHjKTnB39OBN7zrBc#si_PdzIWXUPqtiBHB",
        timestamp: 1709102706561,
        users: 0
    },
    {
        active: 1,
        api_key: "",
        cors: "*",
        created_locale: "KR",
        email: "kkb7528@broadwayinc.com",
        email_triggers: {
            template_setters: {
                invitation: "ap215YqmUTiOMJOKCmGr-tpca05252fb8227531be810e959d100136@mail.skapi.app",
                newsletter_subscription: "ap215YqmUTiOMJOKCmGr-tp75795a7ddc50c31d252afd5c7796a498@mail.skapi.app",
                signup_confirmation: "ap215YqmUTiOMJOKCmGr-tpd7cb9cc07adc726904fa48197b2b1b7f@mail.skapi.app",
                verification: "ap215YqmUTiOMJOKCmGr-tp886587461e82676d00368443c2176e4a@mail.skapi.app",
                welcome: "ap215YqmUTiOMJOKCmGr-tp80763d2756bcba239fde604716d48902@mail.skapi.app"
            }
        },
        group: 2,
        host: "eu71zettahertzesskpi",
        name: "newkkk",
        newsletter_subscribers: 0,
        owner: "5750ee2c-f7f7-43ff-b6a5-cce599d30101",
        region: "ap-northeast-1",
        service: "ap215YqmUTiOMJOKCmGr",
        subsInfo: {
            application: null,
            application_fee_percent: null,
            automatic_tax: {enabled: false, liability: null},
            billing_cycle_anchor: 1709104399,
            billing_cycle_anchor_config: null,
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: {comment: null, feedback: null, reason: null},
            collection_method: "charge_automatically",
            created: 1709104399,
            currency: "usd",
            current_period_end: 1711609999,
            current_period_start: 1709104399,
            customer: "cus_PW1FKUxikUZZ14",
            days_until_due: null,
            default_payment_method: "pm_1Ony4IHfHjKTnB396hlH4Hxf",
            default_source: null,
            default_tax_rates: [],
            description: "Subscription Plan of service ID: ap215YqmUTiOMJOKCmGr",
            discount: null,
            ended_at: null,
            id: "sub_1OohKNHfHjKTnB39OBN7zrBc",
            invoice_settings: {account_tax_ids: null, issuer: {type: 'self'}},
            items: {
                object: 'list', 
                data: [
                    {   
                        billing_thresholds: null,
                        created: 1709104399,
                        id: "si_PdzIWXUPqtiBHB",
                        metadata: {},
                        object: "subscription_item",
                        plan: {
                            active: true,
                            aggregate_usage: null,
                            amount: 1900,
                            amount_decimal: "1900",
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            interval: "month",
                            interval_count: 1,
                            livemode: false,
                            metadata: {},
                            nickname: null,
                            object: "plan",
                            product: "prod_PIoWQwwkbSIBHu",
                            tiers_mode: null,
                            transform_usage: null,
                            trial_period_day: null,
                            usage_type: "licensed"
                        },
                        price: {
                            active: true,
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            custom_unit_amount: null,
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            livemode: false,
                            lookup_key: null,
                            metadata: {},
                            nickname: null,
                            object: "price",
                            product: "prod_PIoWQwwkbSIBHu",
                            recurring: {aggregate_usage: null, interval: 'month', interval_count: 1, trial_period_days: null, usage_type: 'licensed'},
                            tax_behavior: "unspecified",
                            tiers_mode: null,
                            transform_quantity: null,
                            type: "recurring",
                            unit_amount: 1900,
                            unit_amount_decimal: "1900"
                        },
                        quantity: 1,
                        subscription: "sub_1OohKNHfHjKTnB39OBN7zrBc",
                        tax_rates: []
                    }
                ],
                has_more: false, 
                total_count: 1, 
                url: '/v1/subscription_items?subscription=sub_1OohKNHfHjKTnB39OBN7zrBc'
            },
            latest_invoice: "in_1OohKNHfHjKTnB3958nizZVD",
            livemode: false,
            metadata: {owner: '5750ee2c-f7f7-43ff-b6a5-cce599d30101', service: 'ap215YqmUTiOMJOKCmGr'},
            next_pending_invoice_item_invoice: null,
            object: "subscription",
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: {network: null, request_three_d_secure: 'automatic'},
                    customer_balance: null,
                    konbini: null,
                    us_bank_account: null
                },
                payment_method_types: null,
                save_default_payment_method: "off"
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                active: true,
                aggregate_usage: null,
                amount: 1900,
                amount_decimal: "1900",
                billing_scheme: "per_unit",
                created: 1704220828,
                currency: "usd",
                id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                object: "plan",
                product: "prod_PIoWQwwkbSIBHu",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed"
            },
            quantity: 1,
            schedule: null,
            start_date: 1709104399,
            status: "active",
            test_clock: null,
            transfer_data: null,
            trial_end: null,
            trial_settings: {
                end_behavior: {missing_payment_method: 'create_invoice'}
            },
            trial_start: null
        },
        subs_id: "sub_1OohKNHfHjKTnB39OBN7zrBc#si_PdzIWXUPqtiBHB",
        timestamp: 1709102706561,
        users: 0
    },
    {
        active: 1,
        api_key: "",
        cors: "*",
        created_locale: "KR",
        email: "kkb7528@broadwayinc.com",
        email_triggers: {
            template_setters: {
                invitation: "ap215YqmUTiOMJOKCmGr-tpca05252fb8227531be810e959d100136@mail.skapi.app",
                newsletter_subscription: "ap215YqmUTiOMJOKCmGr-tp75795a7ddc50c31d252afd5c7796a498@mail.skapi.app",
                signup_confirmation: "ap215YqmUTiOMJOKCmGr-tpd7cb9cc07adc726904fa48197b2b1b7f@mail.skapi.app",
                verification: "ap215YqmUTiOMJOKCmGr-tp886587461e82676d00368443c2176e4a@mail.skapi.app",
                welcome: "ap215YqmUTiOMJOKCmGr-tp80763d2756bcba239fde604716d48902@mail.skapi.app"
            }
        },
        group: 3,
        host: "eu71zettahertzesskpi",
        name: "newkkk",
        newsletter_subscribers: 0,
        owner: "5750ee2c-f7f7-43ff-b6a5-cce599d30101",
        region: "ap-northeast-1",
        service: "ap215YqmUTiOMJOKCmGr",
        subsInfo: {
            application: null,
            application_fee_percent: null,
            automatic_tax: {enabled: false, liability: null},
            billing_cycle_anchor: 1709104399,
            billing_cycle_anchor_config: null,
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: {comment: null, feedback: null, reason: null},
            collection_method: "charge_automatically",
            created: 1709104399,
            currency: "usd",
            current_period_end: 1711609999,
            current_period_start: 1709104399,
            customer: "cus_PW1FKUxikUZZ14",
            days_until_due: null,
            default_payment_method: "pm_1Ony4IHfHjKTnB396hlH4Hxf",
            default_source: null,
            default_tax_rates: [],
            description: "Subscription Plan of service ID: ap215YqmUTiOMJOKCmGr",
            discount: null,
            ended_at: null,
            id: "sub_1OohKNHfHjKTnB39OBN7zrBc",
            invoice_settings: {account_tax_ids: null, issuer: {type: 'self'}},
            items: {
                object: 'list', 
                data: [
                    {   
                        billing_thresholds: null,
                        created: 1709104399,
                        id: "si_PdzIWXUPqtiBHB",
                        metadata: {},
                        object: "subscription_item",
                        plan: {
                            active: true,
                            aggregate_usage: null,
                            amount: 1900,
                            amount_decimal: "1900",
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            interval: "month",
                            interval_count: 1,
                            livemode: false,
                            metadata: {},
                            nickname: null,
                            object: "plan",
                            product: "prod_PIoWQwwkbSIBHu",
                            tiers_mode: null,
                            transform_usage: null,
                            trial_period_day: null,
                            usage_type: "licensed"
                        },
                        price: {
                            active: true,
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            custom_unit_amount: null,
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            livemode: false,
                            lookup_key: null,
                            metadata: {},
                            nickname: null,
                            object: "price",
                            product: "prod_PIoWQwwkbSIBHu",
                            recurring: {aggregate_usage: null, interval: 'month', interval_count: 1, trial_period_days: null, usage_type: 'licensed'},
                            tax_behavior: "unspecified",
                            tiers_mode: null,
                            transform_quantity: null,
                            type: "recurring",
                            unit_amount: 1900,
                            unit_amount_decimal: "1900"
                        },
                        quantity: 1,
                        subscription: "sub_1OohKNHfHjKTnB39OBN7zrBc",
                        tax_rates: []
                    }
                ],
                has_more: false, 
                total_count: 1, 
                url: '/v1/subscription_items?subscription=sub_1OohKNHfHjKTnB39OBN7zrBc'
            },
            latest_invoice: "in_1OohKNHfHjKTnB3958nizZVD",
            livemode: false,
            metadata: {owner: '5750ee2c-f7f7-43ff-b6a5-cce599d30101', service: 'ap215YqmUTiOMJOKCmGr'},
            next_pending_invoice_item_invoice: null,
            object: "subscription",
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: {network: null, request_three_d_secure: 'automatic'},
                    customer_balance: null,
                    konbini: null,
                    us_bank_account: null
                },
                payment_method_types: null,
                save_default_payment_method: "off"
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                active: true,
                aggregate_usage: null,
                amount: 1900,
                amount_decimal: "1900",
                billing_scheme: "per_unit",
                created: 1704220828,
                currency: "usd",
                id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                object: "plan",
                product: "prod_PIoWQwwkbSIBHu",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed"
            },
            quantity: 1,
            schedule: null,
            start_date: 1709104399,
            status: "active",
            test_clock: null,
            transfer_data: null,
            trial_end: null,
            trial_settings: {
                end_behavior: {missing_payment_method: 'create_invoice'}
            },
            trial_start: null
        },
        subs_id: "sub_1OohKNHfHjKTnB39OBN7zrBc#si_PdzIWXUPqtiBHB",
        timestamp: 1709102706561,
        users: 0
    },
    {
        active: 1,
        api_key: "",
        cors: "*",
        created_locale: "KR",
        email: "kkb7528@broadwayinc.com",
        email_triggers: {
            template_setters: {
                invitation: "ap215YqmUTiOMJOKCmGr-tpca05252fb8227531be810e959d100136@mail.skapi.app",
                newsletter_subscription: "ap215YqmUTiOMJOKCmGr-tp75795a7ddc50c31d252afd5c7796a498@mail.skapi.app",
                signup_confirmation: "ap215YqmUTiOMJOKCmGr-tpd7cb9cc07adc726904fa48197b2b1b7f@mail.skapi.app",
                verification: "ap215YqmUTiOMJOKCmGr-tp886587461e82676d00368443c2176e4a@mail.skapi.app",
                welcome: "ap215YqmUTiOMJOKCmGr-tp80763d2756bcba239fde604716d48902@mail.skapi.app"
            }
        },
        group: 50,
        host: "eu71zettahertzesskpi",
        name: "newkkk",
        newsletter_subscribers: 0,
        owner: "5750ee2c-f7f7-43ff-b6a5-cce599d30101",
        region: "ap-northeast-1",
        service: "ap215YqmUTiOMJOKCmGr",
        subsInfo: {
            application: null,
            application_fee_percent: null,
            automatic_tax: {enabled: false, liability: null},
            billing_cycle_anchor: 1709104399,
            billing_cycle_anchor_config: null,
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: {comment: null, feedback: null, reason: null},
            collection_method: "charge_automatically",
            created: 1709104399,
            currency: "usd",
            current_period_end: 1711609999,
            current_period_start: 1709104399,
            customer: "cus_PW1FKUxikUZZ14",
            days_until_due: null,
            default_payment_method: "pm_1Ony4IHfHjKTnB396hlH4Hxf",
            default_source: null,
            default_tax_rates: [],
            description: "Subscription Plan of service ID: ap215YqmUTiOMJOKCmGr",
            discount: null,
            ended_at: null,
            id: "sub_1OohKNHfHjKTnB39OBN7zrBc",
            invoice_settings: {account_tax_ids: null, issuer: {type: 'self'}},
            items: {
                object: 'list', 
                data: [
                    {   
                        billing_thresholds: null,
                        created: 1709104399,
                        id: "si_PdzIWXUPqtiBHB",
                        metadata: {},
                        object: "subscription_item",
                        plan: {
                            active: true,
                            aggregate_usage: null,
                            amount: 1900,
                            amount_decimal: "1900",
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            interval: "month",
                            interval_count: 1,
                            livemode: false,
                            metadata: {},
                            nickname: null,
                            object: "plan",
                            product: "prod_PIoWQwwkbSIBHu",
                            tiers_mode: null,
                            transform_usage: null,
                            trial_period_day: null,
                            usage_type: "licensed"
                        },
                        price: {
                            active: true,
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            custom_unit_amount: null,
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            livemode: false,
                            lookup_key: null,
                            metadata: {},
                            nickname: null,
                            object: "price",
                            product: "prod_PIoWQwwkbSIBHu",
                            recurring: {aggregate_usage: null, interval: 'month', interval_count: 1, trial_period_days: null, usage_type: 'licensed'},
                            tax_behavior: "unspecified",
                            tiers_mode: null,
                            transform_quantity: null,
                            type: "recurring",
                            unit_amount: 1900,
                            unit_amount_decimal: "1900"
                        },
                        quantity: 1,
                        subscription: "sub_1OohKNHfHjKTnB39OBN7zrBc",
                        tax_rates: []
                    }
                ],
                has_more: false, 
                total_count: 1, 
                url: '/v1/subscription_items?subscription=sub_1OohKNHfHjKTnB39OBN7zrBc'
            },
            latest_invoice: "in_1OohKNHfHjKTnB3958nizZVD",
            livemode: false,
            metadata: {owner: '5750ee2c-f7f7-43ff-b6a5-cce599d30101', service: 'ap215YqmUTiOMJOKCmGr'},
            next_pending_invoice_item_invoice: null,
            object: "subscription",
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: {network: null, request_three_d_secure: 'automatic'},
                    customer_balance: null,
                    konbini: null,
                    us_bank_account: null
                },
                payment_method_types: null,
                save_default_payment_method: "off"
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                active: true,
                aggregate_usage: null,
                amount: 1900,
                amount_decimal: "1900",
                billing_scheme: "per_unit",
                created: 1704220828,
                currency: "usd",
                id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                object: "plan",
                product: "prod_PIoWQwwkbSIBHu",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed"
            },
            quantity: 1,
            schedule: null,
            start_date: 1709104399,
            status: "active",
            test_clock: null,
            transfer_data: null,
            trial_end: null,
            trial_settings: {
                end_behavior: {missing_payment_method: 'create_invoice'}
            },
            trial_start: null
        },
        subs_id: "sub_1OohKNHfHjKTnB39OBN7zrBc#si_PdzIWXUPqtiBHB",
        timestamp: 1709102706561,
        users: 0
    },
    {
        active: 1,
        api_key: "",
        cors: "*",
        created_locale: "KR",
        email: "kkb7528@broadwayinc.com",
        email_triggers: {
            template_setters: {
                invitation: "ap215YqmUTiOMJOKCmGr-tpca05252fb8227531be810e959d100136@mail.skapi.app",
                newsletter_subscription: "ap215YqmUTiOMJOKCmGr-tp75795a7ddc50c31d252afd5c7796a498@mail.skapi.app",
                signup_confirmation: "ap215YqmUTiOMJOKCmGr-tpd7cb9cc07adc726904fa48197b2b1b7f@mail.skapi.app",
                verification: "ap215YqmUTiOMJOKCmGr-tp886587461e82676d00368443c2176e4a@mail.skapi.app",
                welcome: "ap215YqmUTiOMJOKCmGr-tp80763d2756bcba239fde604716d48902@mail.skapi.app"
            }
        },
        group: 51,
        host: "eu71zettahertzesskpi",
        name: "newkkk",
        newsletter_subscribers: 0,
        owner: "5750ee2c-f7f7-43ff-b6a5-cce599d30101",
        region: "ap-northeast-1",
        service: "ap215YqmUTiOMJOKCmGr",
        subsInfo: {
            application: null,
            application_fee_percent: null,
            automatic_tax: {enabled: false, liability: null},
            billing_cycle_anchor: 1709104399,
            billing_cycle_anchor_config: null,
            billing_thresholds: null,
            cancel_at: null,
            cancel_at_period_end: false,
            canceled_at: null,
            cancellation_details: {comment: null, feedback: null, reason: null},
            collection_method: "charge_automatically",
            created: 1709104399,
            currency: "usd",
            current_period_end: 1711609999,
            current_period_start: 1709104399,
            customer: "cus_PW1FKUxikUZZ14",
            days_until_due: null,
            default_payment_method: "pm_1Ony4IHfHjKTnB396hlH4Hxf",
            default_source: null,
            default_tax_rates: [],
            description: "Subscription Plan of service ID: ap215YqmUTiOMJOKCmGr",
            discount: null,
            ended_at: null,
            id: "sub_1OohKNHfHjKTnB39OBN7zrBc",
            invoice_settings: {account_tax_ids: null, issuer: {type: 'self'}},
            items: {
                object: 'list', 
                data: [
                    {   
                        billing_thresholds: null,
                        created: 1709104399,
                        id: "si_PdzIWXUPqtiBHB",
                        metadata: {},
                        object: "subscription_item",
                        plan: {
                            active: true,
                            aggregate_usage: null,
                            amount: 1900,
                            amount_decimal: "1900",
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            interval: "month",
                            interval_count: 1,
                            livemode: false,
                            metadata: {},
                            nickname: null,
                            object: "plan",
                            product: "prod_PIoWQwwkbSIBHu",
                            tiers_mode: null,
                            transform_usage: null,
                            trial_period_day: null,
                            usage_type: "licensed"
                        },
                        price: {
                            active: true,
                            billing_scheme: "per_unit",
                            created: 1704220828,
                            currency: "usd",
                            custom_unit_amount: null,
                            id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                            livemode: false,
                            lookup_key: null,
                            metadata: {},
                            nickname: null,
                            object: "price",
                            product: "prod_PIoWQwwkbSIBHu",
                            recurring: {aggregate_usage: null, interval: 'month', interval_count: 1, trial_period_days: null, usage_type: 'licensed'},
                            tax_behavior: "unspecified",
                            tiers_mode: null,
                            transform_quantity: null,
                            type: "recurring",
                            unit_amount: 1900,
                            unit_amount_decimal: "1900"
                        },
                        quantity: 1,
                        subscription: "sub_1OohKNHfHjKTnB39OBN7zrBc",
                        tax_rates: []
                    }
                ],
                has_more: false, 
                total_count: 1, 
                url: '/v1/subscription_items?subscription=sub_1OohKNHfHjKTnB39OBN7zrBc'
            },
            latest_invoice: "in_1OohKNHfHjKTnB3958nizZVD",
            livemode: false,
            metadata: {owner: '5750ee2c-f7f7-43ff-b6a5-cce599d30101', service: 'ap215YqmUTiOMJOKCmGr'},
            next_pending_invoice_item_invoice: null,
            object: "subscription",
            on_behalf_of: null,
            pause_collection: null,
            payment_settings: {
                payment_method_options: {
                    acss_debit: null,
                    bancontact: null,
                    card: {network: null, request_three_d_secure: 'automatic'},
                    customer_balance: null,
                    konbini: null,
                    us_bank_account: null
                },
                payment_method_types: null,
                save_default_payment_method: "off"
            },
            pending_invoice_item_interval: null,
            pending_setup_intent: null,
            pending_update: null,
            plan: {
                active: true,
                aggregate_usage: null,
                amount: 1900,
                amount_decimal: "1900",
                billing_scheme: "per_unit",
                created: 1704220828,
                currency: "usd",
                id: "price_1OUCt6HfHjKTnB39IwJasJEy",
                interval: "month",
                interval_count: 1,
                livemode: false,
                metadata: {},
                nickname: null,
                object: "plan",
                product: "prod_PIoWQwwkbSIBHu",
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: "licensed"
            },
            quantity: 1,
            schedule: null,
            start_date: 1709104399,
            status: "active",
            test_clock: null,
            transfer_data: null,
            trial_end: null,
            trial_settings: {
                end_behavior: {missing_payment_method: 'create_invoice'}
            },
            trial_start: null
        },
        subs_id: "sub_1OohKNHfHjKTnB39OBN7zrBc#si_PdzIWXUPqtiBHB",
        timestamp: 1709102706561,
        users: 0
    }
]);